TACC/Lmod

init/lmod_bash_completions
with greetings from Basel *hips*
=> fix copy-paste bug in bash completion for restore subcommand

docs/source/030_installing.rst
Most of these are small.  I tried to make the beginning of the User's shells section a little smoother.  Hopefully I did no damage.
=> Some additional small changes

src/utils.lua
Systemwide config files should be in /etc
=> Add a system level lmodrc in /etc

docs/source/010_user.rst, docs/source/015_writing_modules.rst, docs/source/020_advanced.rst, docs/source/030_installing.rst, docs/source/040_FAQ.rst, docs/source/045_transition.rst, docs/source/050_lua_modulefiles.rst, docs/source/060_locating.rst, docs/source/070_standard_modules.rst, docs/source/080_hierarchy.rst, docs/source/090_configuring_lmod.rst, docs/source/095_tcl2lua.rst, docs/source/100_generic_modules.rst, docs/source/110_lmod_mpi_parallel_filesystem.rst, docs/source/120_shared_home_directories.rst, docs/source/130_spider_cache.rst, docs/source/140_deprecating_modules.rst, docs/source/150_kitchen_sink_module.rst, docs/source/index.rst
Fix typos and bugs in Lmod documentation
=> Lomd documentation update

contrib/cache_check/cache_check.lua, contrib/cache_check/readme.md
Simple script to check module dir against system cache - use for notification of outstanding modules not yet added to the system cache.
=> Cache check

README.md
It took me some time to read the project README.md at GitHub. This PR improves layout online while only impacting slightly the layout in terminals and editors.
=> improve layout for grokking README.md

messageDir/fr.lua
This commit adds missing French translations for Lmod messages.
=> Contribute French translations

messageDir/es.lua
I tried to be consistent with Antonio's previous translation. He should review the PR.
=> Added spanish translation for 4 new errors

src/FrameStk.lua
It seems to me sn function is defined 2 times.
=> FIX: Duplicated sn function within FrameStk

messageDir/fr.lua
For the latest batch of messages.
=> provided French translation for various messages

messageDir/de.lua
@wookietreiber can you take a look at this?
=> updated german translation

messageDir/de.lua
removed doubling, quoted command
=> small followup for #244

src/spider.in.lua
=> Update XML generation for new dbT format.

messageDir/de.lua
=> Fixed m_Depend_Mods in German

settarg/settarg_rc.lua
N.B. intel is listed both as compiler and toolchain; this is probably a tension point of definitions. T.B.D. in the future
=> Improve upon default settarg_rc.lua

src/tcl2lua.tcl
Also fix bad variable name in switch statement fallback.
=> Add missing CMake shell in tcl2lua.

docs/source/030_installing.rst
=> Adding mention of Fish setup

init/env_modules_python.py.in
Updated module to work in both python 2 and 3
=> Updated module to work in both python 2 and 3

Makefile.in
=> fix typo in 'make -C pkgs ...' command for 'pkgs' target

Makefile.in, init/fish/module.fish, init/profile.fish.in
I tested with fish shell version 3.0.2
I am not sure about the modifications made in the makefile
closes #407
=> implement tab completion for fish-shell

messageDir/en.lua, rt/spades/err.txt, rt/spider/err.txt, rt/spider_dot/err.txt, rt/tamu/err.txt, rt/uitSitePkg/err.txt
~~(tests will fail, but not due to changes in this PR, see #429)~~
=> suggest using 'module spider' for more information about extensions + break up long message

docs/source/050_lua_modulefiles.rst
Add missing word to description for `setenv` and reword for `os.getenv`
=> Update docs for lua module files

init/profile.in
- change "source" to "." for loading shell specific initialization
files
=> Correct command for shell-specific initialization

init/profile.fish.in
=> add missing quote in fish profile

docs/source/100_modulefile_examples.rst
=> Typo in 100_modulefile_examples.rst

docs/source/090_configuring_lmod.rst
Correct configuration option in docs as well.
=> Issue #532: correct --with-availExtensions in docs

docs/source/090_configuring_lmod.rst
Some typo fixes about the config file part.
=> Fix typo's

docs/source/010_user.rst, docs/source/030_installing.rst, docs/source/040_FAQ.rst, docs/source/080_hierarchy.rst, docs/source/140_deprecating_modules.rst, docs/source/250_site_package.rst
Hi, I noticed some minor copy-editing issues in the FAQ, which are fixed in this PR.  There I also spotted some setup <-> set up mistakes, so I scanned the rest of the docs for those too.
PS. Thanks for this brilliant, invaluable tool!
=> DOCS: Some copyediting fixes

pkgs/tcl2lua/tcl2lua.c
The tcl2lua library is not thread safe. This is apparent with large module directory when building lmod cache (we have spack with ~1200 modules).
Without the patch, running:
```
i=0
while libexec/spider -o spiderT $MODULEPATH > /dev/null; do
i=$((i+1))
echo -n .
done
echo
echo $i
```
will fail after a random number of tries (in our case, usually 2-20 tries) with messages like `free(): invalid pointer`
=> tcl2lua: hopefully thread safe
