TACC/Lmod

- src/update_lmod_system_cache_files.in
Currently dbT files can cause `module spider` to display unreachable modules in some circumstances (see #73). This is a fix for the cache update script so you can give an option that tells it not to create dbT files.
> Added option to not build dbT files on cache update

- src/update_lmod_system_cache_files.in
In the cache update script:
As the default value of $LMOD_REVERSEMAPT_DIR, uses $LMOD_CACHE_DIR, it
should only be set after the defaults are set and checked.
> Set $LMOD_REVERSEMAPT_DIR after $LMOD_CACHE_DIR

- docs/source/030_installing.rst
- docs/source/045_transition.rst
- docs/source/070_standard_modules.rst
Earlier sections used /etc/profile.d/z00_lmod.[sh|csh] and said it was to make them last in the source list; section 4.5 has z99, which would be later.  Changed the earlier references to match z99.
> Regularizing to z99 from z00 naming of /etc/profile.d files

- src/Hook.lua
- src/cmdfuncs.lua
The hook is run after the restore operation and has as argument a table
with the collection, the name of the collection and the path to the
collection file.
@rtmclay It's not very clear to me what the difference is between the `collection` and the `myName` of the collection in the restore function?
> Add hook for restore

- src/Hook.lua
- src/lmod.in.lua
@rtmclay What do you think? Is this the right place?
I've passed `usrCmd` as argument so that together with `masterTbl`, you can have all options passed to Lmod.
Is there a place where all hooks are documented (and I can add this one to)?
> Add startup hook

- src/cmdfuncs.lua
Current, when you do module list:
- If no modules are loaded -> stderr
- If modules are loaded -> depends on LMOD_REDIRECT
This commit makes list always obey LMOD_REDIRECT
> Let module list obey LMOD_REDIRECT

- configure
- configure.ac
By default, I don't have `sha1sum` or `md5sum` available on my OS X system (El Capitan, 10.11.5), but I do have `md5` available in `/sbin`...
@rtmclay I didn't regenerate `configure` from `configure.ac` properly here, but I'm not sure that matters at all for a change this trivial.
> also consider 'md5' as alternative to md5sum

- tools/Dbg.lua
Nice printing of embed tables really helps in debugging/understanding what is going on.
For example, lets print `masterTbl()`:
```
masterTbl:     table
[ignoreCache] boolean false
[defaultOnly] boolean false
[timeout] number 0.0
[version] boolean false
[force] boolean false
[novice] boolean false
[cmdHelpMsg] string 
[expert] boolean false
[initial] boolean false
[cmdHelp] boolean false
[terse] boolean false
[rawDisplay] boolean false
[redirect_off] boolean false
[redirect] boolean false
[dumpversion] boolean false
[debug] number 2
[gitversion] boolean false
[reportTimer] boolean false
[checkSyntax] boolean false
[quiet] boolean false
[availStyle] string system
[config] boolean false
[latest] boolean false
[reportMT] boolean false
[show_hidden] boolean false
[regexp] boolean false …
```
> Nice printing of tables in Dbg

- configure.ac
- src/computeHashSum.in.lua
`sha1sum` is not available on OS X, but `shasum` is:
```
$ shasum README
e3d79ad5a9ffcb8194b94742affa5db9a221a208  README
```
> fall back to 'shasum -a 1' in case sha1sum is not available in computeHashSum

- docs/source/170_hooks.rst
- src/Hook.lua
- src/MasterControl.lua
I pass the full array/table of the error/warning to the hook, so manipulation is possible.
> Extend msgHook to LmodError and LmodWarning

- Makefile.in
- rt/end2end/end2end.tdesc
This fixes the failing `end2end` test in Travis (cfr.#130), because for pull requests to `master` branch isn't there by default when the Lmod repository is cloned; instead, the tests are run on a 'detached head', because Travis tests the *merge commit* rather than the top-level commit of the PR.
This change should be backward compatible, and the fix is verified in Travis (cfr. https://travis-ci.org/boegel/Lmod/jobs/138170813).
> make git branch tweakable for 'make dist'

- src/utils.lua
This also refers to #130: installing `uuidgen` on Travis is kind of difficult because the `uuid-runtime` package can not be installed via the usual `apt-get` (yet, it is not whitelisted yet because of potential security issues).
With this fallback in place, the `hook` test passes on Travis (cfr. https://travis-ci.org/boegel/Lmod/jobs/138178684), where it previously failed with `sh: 1: uuidgen: not found`
@rtmclay I also noticed that the `configure` script isn't checking whether `uuidgen` is available at all, even though Lmod does call out to `uuidgen` sometimes... That should probably be fixed as well (with this fallback in mind)?
> use /proc/sys/kernel/random/uuid as fallback in case uuidgen is not available

- tools/capture.lua
I need this change (together with #134) to make all tests pass on my system (OS X El Capitan w/ Lua 5.1 installed via the tarball provided in the Lmod repo)
> fix determining of exit status in capture function for Lua 5.1

- .travis.yml
- rt/common_funcs.sh
- rt/delcatty/delcatty.tdesc
- rt/delcatty/err.txt
- rt/errHandler/err.txt
- rt/errHandler/errHander.tdesc
- rt/modulerc/err.txt
- rt/modulerc/modulerc.tdesc
This is not ready yet, currently 5 tests are failing on Travis (cfr. https://travis-ci.org/boegel/Lmod/builds/136810652). Also, I may squash all commits here, it's a bit messy now.
```
diff     /home/travis/build/boegel/Lmod/rt/delcatty/t1/2016_06_10_21_06_32-Linux-x86_64-delcatty
diff     /home/travis/build/boegel/Lmod/rt/end2end/t1/2016_06_10_21_06_32-Linux-x86_64-end2end
diff     /home/travis/build/boegel/Lmod/rt/errHandler/t1/2016_06_10_21_06_32-Linux-x86_64-errHandler
diff     /home/travis/build/boegel/Lmod/rt/hook/t1/2016_06_10_21_06_32-Linux-x86_64-hook
diff     /home/travis/build/boegel/Lmod/rt/modulerc/t1/2016_06_10_21_06_32-Linux-x86_64-modulerc
```
My analysis:
* `delcatty`, `errHandler` and `modulerc` fails because of line wrapping; I tried to fix this by defining …
> add Travis config for Lmod test suite

- src/MName.lua
- src/Master.lua
Doing something like:
```bash
$ ml zlib
$ ml zlib
```
will now work. It will detect that the default version is already loaded and just reload.
> Also return version in MName

- init/lmod_bash_completions
* Added support for ${LMOD_REDIRECT}
* Fixed bug where "ml rm <TAB>" would list all available modules as opposed to loaded ones that can be removed.
* Indentation used a mix of tabs and spaces: standardized for now on tabs for indentation.
> Improved lmod_bash_completions

- src/utils.lua
- tools/capture.lua
In very particular circumstances (*cough* EasyBuild *cough*), we were seeing problems where the subshell that is forked by the `io.popen` via `capture` was broken because of an `$LD_PRELOAD` being set without that the paths to the libraries reloaded by that preloaded library are listed in `$LD_LIBRARY_PATH`
This patch (partially) fixes this problem, by resetting `$LD_LIBRARY_PATH` and `$LD_PRELOAD` *before* `capture`, rather than as a part of the command being executed by `capture`.
Although this patch fixes the problem we are seeing, it seems like this patch is incomplete, since the error caused by the preloaded library also seems to be occurring in other (less destructive) places.
A better fix may be to simply *always* hard reset `$LD_LIBRARY_PATH` and `$LD_PRELOAD` in `capture` (or …
> reset $LD_LIBRARY_PATH and $LD_PRELOAD before forking off shell to run tcl2lua

- init/lmod_bash_completions
* Renamed `_module_filedir` function to `_module_dir` as it only handles dirs and not files.
* Added support for environment variables to _module_dir, so they can be used in `ml use` and `module use` commands.
* Autocompleted environment variables are filtered for ones that contain existing directory paths, so you will only get relevant autocomplete suggestions.
* Added support for `~` to _module_dir, so we can expand to the user's home dir in `ml use` and `module use` commands.
* Fixed mis-indentation after `if`, where 4 spaces per indentation level were used whereas all other lines used only 2.
* Completely removed the dependency on `_filedir` function from the bash_completion package: the custom `_module_dir` function is now more advanced than the standard `_filedir` and no longer the …
> Added support for environment variables as well as ~ in bash autocompletion.

- docs/source/070_standard_modules.rst
is there a reason for not having it that way already?!
> LMOD_SYSTEM_DEFAULT_MODULES should be conditional on not being predefined elsewhere

- src/MasterControl.lua
In our hooks that change the output of warnings and errors, it's quite annoying to have an empty line if the stack trace is empty. This will only add the module stack trace when it's non-empty.
> Only print module strack when it's non-empty

- rt/help/err.txt
- src/Configuration.lua
- src/Options.lua
- src/lmod.in.lua
- src/ml_cmd.in.lua
This option will dump the current Lmod configuation as json to stderr.
It contains the same information as --config.
```
$ ml --config-json 2>&1| python -mjson.tool
{
"cache": [
[
"/apps/gent/lmodcache",
"/apps/gent/lmodcache/timestamp"
]
],
"config": {
"allowTCL": "yes",
"autoSwap": "no",
"case": "yes",
"colorize": "yes",
"disable1N": "yes",
"dot_files": "yes",
"dupPaths": "no",
"exactMatch": "no",
"expMCmd": "YES",
"ld_lib_path": "<empty>",
"ld_preload": "<empty>",
"lmodV": "6.5.17-1-gfe3b4b6",
"luaV": "Lua 5.3",
"lua_json": "yes",
"lua_term": "yes",
"lua_term_A": "true",
"modRC": "/home/ward/tmp/Lmod/install/lmod/etc/rc",
"mpath_av": "no",
"mpath_root": "/etc/modulefiles/vsc",
"numSC": 1,
"ordering": "modern",
"pager": "/usr/bin/less",
"pager_opts": "-XqMREF",
"path_hash": …
```
> Add a --config-json option

- .travis.yml
- init/r.in
- rt/R/R.tdesc
- rt/R/err.txt
@wpoely86 was correct. This PR augments `.travis.yml` to install R on travis and enables the test for R as an output shell.
> Enable R testing on travis

- tools/TermWidth.lua
When term is set to an empty string tput prints an error message on our cluster:
```tput: No value for $TERM and no -T specified```
> TERM can be set with an empty value which results in a tput error

- README.md
There's command like hide-module. The proper way is use hide-version.
```
[easybuild@login4.salomon ~]$ cat .modulerc 
#%Module
hide-module git/2.8.0
```
```bash
[easybuild@login4.salomon ~]$ module load lmod
invalid command name "hide-module"
while executing
"hide-module git/2.8.0"
(file "/home/easybuild/.modulerc" line 3)
invoked from within
"source $mRcFile"
(procedure "main" line 6)
invoked from within
"main /home/easybuild/.modulerc"
("eval" body line 1)
invoked from within
"eval main $argv"
(file "/apps/all/Lmod/7.0.6/lmod/lmod/libexec/RC2lua.tcl" line 89)
Lmod has detected the following error:  Unable to parse: /home/easybuild/.modulerc  Aborting!
```
Correct way:
```bash
[easybuild@login4.salomon ~]$ cat .modulerc 
#%Module
hide-version git/2.8.0
```
```bash …
```
> Correction to hide command - README

- messageDir/de.lua
This adds all the messages currently defined in messageDir/en.lua in German.
Is there a reason for multiple consecutive spaces (e. g. before variables in strings and after punctuation), for missing punctuation at the end of messages, and different formatting of multiline text? For now I mimicked the English translation.
Are non-ASCII characters allowed (especially ä/ö/ü/ß)? The previous German translation used ae/oe/... for these.
@wookietreiber: could you also take a look at this?
> expanded German translation

- docs/source/170_hooks.rst
A new hook errWarnMsgHook is not documented. Since it might break most of the SitePackage.lua instances it's good to document it ASAP.
> Added missing errWarnMsgHook in the documentation

- src/MasterControl.lua
A message gets composed from the string in messageT.lua and the keys
that are passed. Before, the hook only got the fully composed message.
With this commit, we pass both the full message and the keys used to
compose it. This gives you a bit more flexibility. 
You can now adjust the message the user sees and use logic based on
the 'input' (the keys).
But it of course breaks existing errWarnMsgHooks...
> Extend the errWarnMsgHook to also pass the keys of the message

- contrib/more_hooks/README.md
- contrib/more_hooks/SitePackage.lua
Specifically for EasyBuild, this will give you:
```
$ ml purge
$ ml ncurses/5.9-intel-2015a
$ ml ncurses/5.9-intel-2015b
Lmod has detected the following error:  A different version of the 'ncurses' module is already loaded (see output of 'ml').
If you don't understand the warning or error, contact the helpdesk at <email> 
$ ml libreadline/6.3-intel-2014b
Lmod has detected the following error:  A different version of the 'intel' module is already loaded (see output of 'ml').
You should load another 'libreadline' module for that is compatible with the currently loaded version of 'intel'.
Use 'ml spider libreadline' to get an overview of the available versions.
If you don't understand the warning or error, contact the helpdesk at <email> 
While processing the following module(s):
Module …
```
> Update contrib hooks

- src/LocationT.lua
I do not know why, but under certain circumstances Lmod tried to call `pairs(T)`, with `T` being `nil`:
```
/usr/bin/lua: ...cal/software/juropa3/lmod/lmod/libexec/LocationT.lua:101: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
...cal/software/juropa3/lmod/lmod/libexec/LocationT.lua:101: in function 'build'
...cal/software/juropa3/lmod/lmod/libexec/LocationT.lua:116: in function 'new'
...local/software/juropa3/lmod/lmod/libexec/ModuleA.lua:479: in function 'search'
...r/local/software/juropa3/lmod/lmod/libexec/MName.lua:184: in function 'lazyEval'
...r/local/software/juropa3/lmod/lmod/libexec/MName.lua:238: in function 'fn'
.../local/software/juropa3/lmod/lmod/libexec/Master.lua:461: in function 'reloadAll' …
```
> Fixed bug in LocationT.lua, where sometimes Lmod tried to interate over nil

- src/cmdfuncs.lua
An incorrect table was passed as an argument.
> Fix msgHook on list

- docs/source/070_standard_modules.rst
- docs/source/220_tracing.rst
- my_docs/17/TACC_sysadmin_17/talk.tex
I was following the installation instructions and noticed some odd behavior. If I setup `z00_lmod.sh` and `z00_StdEnv.sh` as suggested in the tutorial and try logging in, I see the following error message:
```
bash: module: command not found
```
`z00_lmod.sh` defines the `module` command, while `z00_StdEnv.sh` runs `module restore`. The problem is that capital S sorts before lowercase L, at least on my system, and so `z00_StdEnv.sh` is sourced before `z00_lmod.sh`. We have a few options to solve this:
1. Rename `z00_lmod.sh` -> `z00_Lmod.sh`
2. Rename `z00_StdEnv.sh` -> `z00_stdenv.sh`
3. Rename `z00_StdEnv.sh` -> `z01_StdEnv.sh`
This PR currently does 1, but now that I think about it 3 is probably safer. Thoughts?
> Rename z00_StdEnv.sh for proper order of sourcing

- src/Var.lua
This seems to fix the problem we are seeing where the Lmod cache file is not always being used, which results in slow `module load` commands even though we have cached loads enabled.
Without this patch:
```
$ ml --force purge; time ml cluster
real	0m2.505s
user	0m0.516s
sys	0m0.257s
$ ml --force purge; time ml cluster
real	0m2.201s
user	0m0.497s
sys	0m0.256s
$ ml --force purge; time ml cluster
real	0m2.445s
user	0m0.472s
sys	0m0.281s
```
```
$ grep '^open.*SL6.*' strace_no_patch.out  | wc -l
3511
```
with patch:
```
$ ml --force purge; time ml cluster
real	0m0.333s
user	0m0.273s
sys	0m0.058s
$ ml --force purge; time ml cluster
real	0m0.334s
user	0m0.266s
sys	0m0.067s
$ ml --force purge; time ml cluster
real	0m0.332s
user	0m0.301s
sys	0m0.029s
```
```
$ grep '^open.*SL6.*' …
```
> make sure spider cache is being used in chkMP

- src/tcl2lua.tcl
Unless I'm missing something, it looks like the new `depends_on` functionality was not extended to tcl parsing. 
This is a quick start at enabling. Presumably keywords like `always_load` may also want to be registered.
> extend new depends_on keyword to tcl as depends-on

- src/ModuleA.lua
`l_checkforNV` was failing because `T` was `nil`. Lmod < 7.6 worked properly. This fixes it.
> Fixed nil argument in checkforNV

- Makefile.in
- init/fish.in
- init/profile.fish.in
This is a collection of fixes to problems outlined in #334 for fish shell support in lmod.
To get Fish working for Lmod, you should link your `init/profile.fish` file into one of fish's `conf.d` directories. You could also do:
```
source (brew --prefix lmod)/lmod/init/fish
set -gx MODULEPATH /usr/local/Cellar/lmod/7.6.11/modulefiles/Darwin:/usr/local/Cellar/lmod/7.6.11/modulefiles/Core:/usr/local/Cellar/lmod/7.6.11/lmod/modulefiles/Core
```
where MODULEPATH comes from the bash version.
> Fixes for fish init

- init/profile.fish.in
In #335 I made a typo; `-n` turned into `-z`. In worked running fish from bash but failed when running fish as a default shell. This fixes the typo.
> Fix fish typo

- src/tcl2lua.tcl
I was getting the following message while trying to load a legacy tcl module:
`$ module load 7.6.00alpha_rev7690-ompi
Lmod has detected the following error:
/apps/[...]/7.6.00alpha_rev7690-ompi: (7.6.00alpha_rev7690-ompi): can't read
"cmdArgsL": no such variable
While processing the following module(s):
Module fullname           Module Filename
---------------           ---------------
7.6.00alpha_rev7690-ompi  /apps/[...]/7.6.00alpha_rev7690-ompi
`
After applying the fix, it just works fine.
> Bugfix: Check if variable "cmdArgsL" exists before using it.

- docs/source/010_user.rst
Last sentence of first paragraph in [ml: A convenient tool](https://lmod.readthedocs.io/en/latest/010_user.html#ml-a-convenient-tool) section needs a space to remove the asterisks.
Thanks for Lmod :blush:
> [docs] add space to remove asterisks from rendering

- docs/source/300_tracking_module_usage.rst
The paired quote marks used on the doc page for the suggested rsyslog.conf modification don't work with rsyslog if the text is copy and pasted. This replaces them with single unpaired quote marks.
> Fix quote marks in rsyslog.conf modification

- Makefile.in
- init/profile.fish.in
thanks @kcgthb for your commits. Now it works. There was a bug because I was overwriting the `fish` executable. Now should be fixed
> fix path for fix shell

- docs/source/200_avail_custom.rst
I added a brief explanatory text motivating use of the grouped
labeling.
At the end of the document, I added some text from
https://sourceforge.net/p/lmod/mailman/message/32759572/
where you had a clear and more complete explanation of the use
of MODULE_AVAIL_STYLE.
We are looking at EasyBuild, but we are using our current Lmod
installation, for which we export MODULE_AVAIL_STYLE=grouped,
and while we are looking at EB, it's more useful to change back
to the system style.  I didn't find anything to revert in the
Lmod documentation, and this is the result.
> Adding additional explanatory text about LMOD_AVAIL_STYLE

- init/bash.in
This just does the same thing as fa2e3a1a, but for two more
similar echo statements that were missed.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
> Redirect two more echo stmt to stderr in init/bash.in

- docs/source/030_installing.rst
The prior text used the term `libtcl` which isn't a package name in CentOS.
I changed that to `tcl-devel` and reworded the text.
I added a paragraph break before enumerating the Ubuntu packages.
I sorted the list of installed Lua packages to match what `rpm -qa` produces
to facilitate comparison between installed and documented packages.
I moved the install tcl-devel package name to its own block, as the text
describes the Lua packages, then the TCL packages, and I added the package
name for the main tcl package.
There is an EPEL package, `tcllib`, which is not, I believe, required for Lmod, and was
the source of my confusion, hence this PR.
```
Name        : tcllib
Arch        : noarch
Version     : 1.14
Release     : 1.el7
Size        : 8.9 M
Repo        : installed
From repo   : epel …
```
> Changed text to make which tcl libraries needed for CentOS 7.

- src/sandbox.lua
We wanted to do some basic math in a module and I noticed that there are no math functions in the sandbox. I've added a couple of the most useful ones (given that bash only knows about integers).
Use case: setting the stack size of java to 80% of the memory inside a job automatically.
> Add basic math functions to module sandbox

- contrib/more_hooks/README.md
- contrib/more_hooks/SitePackage.lua
It's just an example how to figure out the maximum allowed memory inside
the environment of a module (if any limit is set at all).
> Add example function get_avail_memory to the sandbox

- src/cmdfuncs.lua
Many commands go quiet when the "-q" option or LMOD_QUIET environment variables are set, but module reset was ignoring it. This PR addresses that problem by adding a simple check before issuing the m_Reset_SysDflt message.
> Honour quiet option in module reset

- init/profile.fish.in
correct the LMOD_ALLOW_ROOT_USE logic.
> allow root user to use lmod in fish shell

- docs/source/030_installing.rst
I might be wrong but seems like the intention would be to use `setopt no_nomatch`
for the entire loop and not just the first file.
> Possibly incorrect opt placement for zsh

- src/cmdfuncs.lua
This fixes a minor bug which caused an error when using `module --terse keyword`  as the `providedByT` argument was missing when calling the `Level0_terse` function.
> adding providedByT argument to Level0_terse when using 'module keyword' in combination with '--terse'

- docs/source/125_personal_spider_cache.rst
As of https://github.com/TACC/Lmod/blob/master/src/myGlobals.lua#L526 the default is 2 seconds not 10.
> Correct default for LMOD_SHORT_TIME

- init/fish.in
It seems the `tcl2lua.tcl` need `LMOD_VERSION`, the [current fish init script](https://github.com/TACC/Lmod/blob/master/init/fish.in) does not set it, leading to the following error
```
/usr/share/lmod/8.4.28/libexec/tcl2lua.tcl dft
no such variable
(read trace on "env(LMOD_VERSION)")
invoked from within
"set ModuleToolVersion $env(LMOD_VERSION)"
(procedure "execute-modulefile" line 5)
invoked from within
"execute-modulefile $modfile"
(procedure "main" line 5)
invoked from within
"main dft"
("eval" body line 1)
invoked from within
"eval main $argv"
(file "/usr/share/lmod/8.4.28/libexec/tcl2lua.tcl" line 1020)
```
> Set LMOD_VERSION for fish-shell

- docs/source/050_lua_modulefiles.rst
- src/MC_ComputeHash.lua
- src/Master.lua
- src/MasterControl.lua
- src/Var.lua
- src/addto.in.lua
- src/modfuncs.lua
- src/sh_to_modulefile.in.lua
- src/utils.lua
Basically all sep named variables has been
changed to delim. Only a few places (string_utils) are
they unchanged since it doesn't really affect the Lmod
base as much.
This is just to clarify for developers a coherence between
the documentation and the implementation.
I have also added another cmd argument with --delim
which behaves similar to --sep.
> mnt: changed internal sep name to delim

- Makefile.in
- docs/source/030_installing.rst
- docs/source/index.rst
- init/profile.rc.in
- init/rc.in
- shells/BaseShell.lua
- shells/Rc.lua
- src/tcl2lua.tcl
This patch adds support for the `rc` shell (https://github.com/benavento/rc).
rc has far fewer issues with quotations than most shells, usually just requiring
transforming `str` into `"'" .. str:gsub("'", "''") .. "'"`
The second commit adds the install-line for `init/profile.rc` into the `Makefile` and teaches `libexec/tcl2lua.tcl` to recognize rc.
> Added rc support.

- rt/help/err.txt
- rt/i18n/err.txt
- src/lmod.in.lua
I noticed today that `module help` said:
```
overview | ov                     List all available modules by short names with number of versions
overview | av       string        List available modules by short names with number of versions that contain "string"
```
and I figured that should be an `ov` on the second line.
After fixing those up, I also decided to try my hand at doing a French translation in `rt/i18n/err.txt`. My baby-level-on-Duolingo and Google Translate attempt is contained herein.
> Fix overview help typos (and try translation)

- .readthedocs.yml
- docs/requirements.txt
Lmod docs build for `master` branch is failing currently, see https://readthedocs.org/projects/lmod/builds/15214716/.
The problem is caused by a mismatch between Sphinx 1.8.5 (which is *old*) and latest docutils, see https://github.com/readthedocs/readthedocs.org/issues/8616, https://github.com/sphinx-doc/sphinx/issues/9811 and https://github.com/sphinx-doc/sphinx/issues/9783, among others.   
The problem only occurs for old project on ReadTheDocs, which still default to `sphinx<2`; see https://docs.readthedocs.io/en/stable/builds.html#python .
The proposed change is the easy way out, by pinning to an old `docutils` version that is compatible with Sphinx 1.8.5 (most recent Sphinx version < 2).
A better long-term approach would be to pin to a more recent version of Sphinx (and perhaps also …
> fix building of Lmod documentation on ReadTheDocs by pinning to old Sphinx/docutils version

- src/Master.lua
We have nested sticky modules, which is to say, module A adds a module path containing module B, both of which are sticky.  If you load A and B, and then `module purge`, you end up with only module A loaded, and B not.  This is because the modules are unloaded in reverse order (B, A), and added to the sticky list in this order, and thus reloaded in this order: B (not found, since it's under A), then A.  Reversing the reload order in `reload_sticky` seems to fix this.  (Could also add them to stickyA in reverse order but this seems easier.
> reload_sticky in reverse order to match load order on purge

- init/profile.in
The fixes for TACC#544 (commit 557ede614d3e188fb7c1497b90d979c73f67da2a) broke the support for ksh. 
Here is a proposed simplification of the relevant bit so it brings back the support for any version of ksh.
> Fixed ksh support broken with TACC#544 fixes

- init/bash.in
- init/ksh_funcs/ml
- init/ksh_funcs/module
- init/sh.in
A more generic solution to the pathname expansion issue (fixed for Bash
with the use of set -f/set +f) is to quote the code generated as output
by the 'lmod' command to pass it to the shell 'eval' command.
The pathname expansion issue also affects ksh93 and bash-variant of sh
shells. Quoting generated code in the module/ml shell functions of these
shells will help here too.
This change was just applied on Modules and from the tests made, I have
seen that it also fix some script shell evaluations performed through
source-sh.
With this change, the set -f/set +f code applied around lmod command
execution in module bash shell function could be removed. Which will
help to fix #569.
> Quote code generated by lmod cmd to pass it to eval

- tools/serializeTbl.lua
We wrote some code that makes use of serializeTbl( ) and stumbled upon this little (I presume) typo. It's minor but I felt it was worth fixing it upstream.
> Fix function call in serializeTbl()

- contrib/more_hooks/SitePackage.lua
We tripped an Lmod error that broke the logging because of quotes and ( ). This fixes it.
@boegel FYI
> Custom SitePackagelua: use safe printing for log lines

- src/ml_cmd.in.lua
The '--config-json' option was renamed to '--config_json' for 'module' in f3f1ac84993f1d5b630fcfcd5f60aa52d7bdaea7
but not in 'ml'.
> Fix ml to accept option '--config_json' as does module

- src/Options.lua
In 8.7.25 the option -f was introduced as alias for --force in the ml command. Now updating Options.lua to make the module command consistent again.
> -f as alias for --force in module command

- pkgs/tcl2lua/Makefile
install will dereference symbolic links.
On a somewhat related question - will it cause problems if I install tcl2lua.so* to a different location?  What uses it and how to test?  Thanks.
> Do not use install to copy symbolic links

- docs/source/040_FAQ.rst
Variable name (i.e., `::env(LMOD_VERSION_MAJOR)`) should be used against `info exists` Tcl command to check variable existence rather variable value (i.e., `$::env(LMOD_VERSION_MAJOR)`), which will raise an error if variable does not exist.
> doc: fix `info exists` Tcl example in FAQ

- src/utils.lua
https://github.com/tacc/lmod/issues/603
> colorize the version numbers in `ml av` with env. var.

- shells/BaseShell.lua
- shells/JsonShell.lua
- src/tcl2lua.tcl
Adapted the python shell to make a simple json reporter.
Analyzing how this implementation behaves shows a few issues:
- The reported json object represents only the actions, not the current state of the module. So then what should the json interface report:
- Specific actions of `set`/`unset`/`shell_function` etc. as specific keys to the json object? Then the consumer would have to keep track of the state of the environment variables setting/unsetting/updating
- Expand the base table in the lua script and just output the final state
- Commands like `module list` do not produce a meaningful `tbl` to be exported as json
> Add simple `JsonShell`

- src/Hook.lua
Note: there is an alternative approach in [another PR](https://github.com/TACC/Lmod/pull/695). However, I consider the approach in this (#696) PR cleaner, because it is more explicit.
This PR stores hooks in `Hook.lua` internally as tables. It also adds the additional possibility of appending hooks to this table: a third (boolean) argument can be passed to `hook.register` that defines if the function should be appended (`true`) to the exist function, or whether it should overwrite it (`false`). The default value if this argument is _not_ specified is `false`, to maintain backwards compatibility.
It can be tested with this simple `SitePackage.lua`:
```
require("strict")
local hook = require("Hook")
local function load_hook_a(t)
local frameStk  = require("FrameStk"):singleton()
local mt …
```
> Allow registering multiple hooks of the same type - alternate approach

- init/lisp
- shells/Lisp.lua
> fix emacs integration 

- init/cshrc.in
At LANL we've patched this for some time apparently. If BASH_ENV is set in `init/cshrc` then csh users won't be able to run bash scripts, which our users need to be able to do.
> Add check before setting BASH_ENV cshrc.in

- docs/source/140_deprecating_modules.rst
- src/utils.lua
I wasn't sure if I could add comments to my admin file. The source code says I can, but only if the `#` character is at the very beginning. 
https://github.com/TACC/Lmod/blob/b46bcc82b9b37700b84bb0283cec172eda01e5eb/src/utils.lua#L423-L425
Updated the docs and made it so that comments are recognized even if there is witespace before it.
tested:
```
$ env -iS /bin/bash --norc --noprofile
bash-5.0$ source ~/Lmod-build/lmod/lmod/init/profile
bash-5.0$ export LMOD_ADMIN_PATH=/home/simonleary_umass_edu/Lmod-test/adminfile
bash-5.0$ module --config 2>&1 | grep 'Admin file'
Admin file                                                    /home/simonleary_umass_edu/Lmod-test/adminfile
bash-5.0$ cat /home/simonleary_umass_edu/Lmod-test/adminfile
lmod:
hello, world!
bash-5.0$ ml lmod …
```
> update docs, allow comments in admin file with leading whitespace

- messageDir/en.lua
Commit 15224be i18n-ified the closing border for `reportAdminMsgs` but it dropped the newlines. This results in the user's prompt starting in the last column next to the border
```
[root@login04 ~]# su - user
--------------------------------------------------------------------------
There are messages associated with the following module(s):
--------------------------------------------------------------------------
DefApps:
test message
--------------------------------------------------------------------------[user@login04~]$
```
> Ensure m_Module_Msgs_close has newlines

- src/cmdfuncs.lua
Possible fix for #753 
I haven't been able to confirm this actually fixes the problem I reported via #753, but it sort of makes sense to me...
I can't reproduce the crash on `module unuse` locally (on my MBP, macOS 14.6.1, Lua 5.4.7) very easily with Lmod 8.7.57, I only see it on our HPC system (RHEL9.4, Lua 5.4.4).
> always set display mode for unuse command

- docs/source/370_irreversible.rst
Sub-lists in "mode select" documentation were not rendered correctly due to an incorrect number of space character prefix.
> Fix RST sub-lists in mode select doc

- tools/fileOps.lua
```console
$ bash -c '. /usr/share/lmod/lmod/init/profile; unset PATH; module --version'
/usr/bin/lua5.3: /usr/share/lmod/lmod/libexec/../tools/fileOps.lua:76: attempt to index a nil value (local 'path')
stack traceback:
/usr/share/lmod/lmod/libexec/../tools/fileOps.lua:76: in function 'findInPath'
/usr/share/lmod/lmod/libexec/pager.lua:87: in function 'buildPager'
/usr/share/lmod/lmod/libexec/pager.lua:97: in main chunk
[C]: in function 'require'
/usr/share/lmod/lmod/libexec/lmod:111: in main chunk
[C]: in ?
```
> allow unset PATH

- contrib/tracking_module_usage/gen_2/createDB.py
It looks like this code was developed over time using a different Python MySQL module than the current recommended module. This change modifies the exception handling to use the recommended module.
> contrib: Fix createDB error reporting

- docs/source/051_tcl_modulefiles.rst
- rt/tclmodules/err.txt
- rt/tclmodules/mf/help/1.0
- rt/tclmodules/mf/help/2.0
- rt/tclmodules/out.txt
- rt/tclmodules/tclmodules.tdesc
- src/tcl2lua.tcl
The "module-help" modulefile command has been introduced in Environment Modules 5.6 to provide a way to define help messages simpler than the traditional ModulesHelp procedure, like achieved on Lua modulefiles with the "help()" function.
This commit adds "module-help" support for Tcl modulefiles and make it map to the "help()" Lua function when translated by tcl2lua.tcl.
> Add module-help support for Tcl modules

- docs/source/051_tcl_modulefiles.rst
- rt/tclmodules/err.txt
- rt/tclmodules/mf/report/1.0
- rt/tclmodules/out.txt
- rt/tclmodules/tclmodules.tdesc
- src/tcl2lua.tcl
The "report" modulefile command is available in Environment Modules to provide a way for modulefile developer to print text to user, like achieved on Lua modulefiles with the "LmodMessage()" function.
This commit adds "report" support for Tcl modulefiles and make it map to the "LmodMessage()" Lua function when translated by tcl2lua.tcl.
> Add "report" support for Tcl modules

- docs/source/051_tcl_modulefiles.rst
"extensions" Tcl modulefile command accepts a list of argument. Fix documentation that stated the command accepts a single string.
> doc: fix doc of "extensions" Tcl modulefile command
